### ISSUE TITLE
German letters

### ISSUE THREAD

**Issue by supertobi** [inkstitch/embroidery-fonts#1]
It would be really cool if you could add the German umlaut (äöüÄÖÜ) and the eszett (ß) to your font.

**Comment by lexelby** [comment]
Sure!  I'm actually in the process of adding lettering support to Ink/Stitch.  It uses SVGs for the fonts, one layer per character.  You can see it here: https://github.com/inkstitch/inkstitch/pull/344

I'll take a shot at adding those characters, but hopefully it should also be easy enough for you or others to add characters too.
